import re

TSQL_SYMBOLIC = re.compile(r'<@(?P<symb>[0-9]+)>', flags=re.MULTILINE)
TSQL_SYMBOLIC_OUTER = re.compile(r'(?P<outer_symb><@[0-9]+>)[\.\^]?((<@[0-9]+>[\.\^-]?)+)?', flags=re.IGNORECASE | re.MULTILINE)
IS_SQL_QUERY = re.compile(r'\(.*(?=(SELECT)).*\)', flags=re.IGNORECASE | re.MULTILINE)
TSQL_STATEMENTS = re.compile(r'\s*(WITH|SELECT|FROM|WHERE|GROUP BY|ORDER BY|OFFSET|FETCH)\s*', flags=re.IGNORECASE | re.MULTILINE)
TSQL_ROWOPS = re.compile(r'\s*(INTERSECT|EXCEPT|UNION ALL|UNION)\s*', flags=re.IGNORECASE | re.MULTILINE)
TSQL_VARTABLE_NAMED = re.compile(r'(?=([\"\[]?(?P<table>[<>@A-Za-z0-9_]+)[\"\]]?\.[\"\[]?(?P<varname>[<>@A-Za-z0-9_]+|[\*])[\"\]]?(\s+AS\s+|\s)[\"\']?(?P<alias>[<>@A-Za-z0-9_]+)[\"\']?\s*(,|$)))', flags=re.IGNORECASE | re.MULTILINE)
TSQL_VARTABLE_UNNAMED = re.compile(r'(?=([\"\[]?(?P<table>[<>@A-Za-z0-9_]+)[\"\]]?\.[\"\[]?(?P<varname>[<>@A-Za-z0-9_]+|[\*])[\"\]]?\s*(,|$)))', flags=re.IGNORECASE | re.MULTILINE)
TSQL_VAR_NAMED = re.compile(r'(?=([^\.][\"\[]?(?P<varname>[<>@A-Za-z0-9_]+|[\*])[\"\]]?(\s+AS\s+|\s)[\"\']?(?P<alias>[<>@A-Za-z0-9_]+)[\"\']?\s*(,|$)))', flags=re.IGNORECASE | re.MULTILINE)
TSQL_VAR_UNNAMED = re.compile(r'(?=([^\.][\"\[]?(?P<varname>[<>@A-Za-z0-9_]+|[\*])[\"\]]?\s*(,|$)))', flags=re.IGNORECASE | re.MULTILINE)
TSQL_SUBQUERY_ALIAS_PREFIX = re.compile(r'[\"\[]?(?P<alias>[A-Za-z0-9_]+)[\"\]]?\s+AS\s+\(', flags=re.IGNORECASE | re.MULTILINE)
TSQL_SUBQUERY_ALIAS_SUFFIX = re.compile(r'\)(\s+AS\s+|\s+)[\"\']?(?P<alias>[A-Za-z0-9_]+)[\"\']?\s*(,|$)', flags=re.IGNORECASE | re.MULTILINE)
TSQL_CTES = re.compile(r'\s*(?P<alias>[A-Za-z0-9_]+)\s+AS\s+(?P<table>[<>@A-Za-z0-9_]+)(\s|,|\.|$)', flags=re.IGNORECASE | re.MULTILINE)
TSQL_JOIN_JOINTYPES = re.compile(r'\s*(?P<jointype>(FULL OUTER JOIN|LEFT OUTER JOIN|RIGHT OUTER JOIN|FULL JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|CROSS JOIN|SELF JOIN|JOIN))\s+', flags=re.IGNORECASE | re.MULTILINE)
TSQL_JOIN_MAJOROPS = re.compile(r'(?P<majop>(ON|AND|OR))', flags=re.IGNORECASE | re.MULTILINE)
TSQL_JOIN_ALLOPS = re.compile(r'(?P<op>\s+(<>|!=|>=|<=|!<|!>|\+=|\-=|\*=|/=|%=|&=|\|=|\^=|\|\||IS NOT NULL|IS NULL|NOT IN|AND|OR|NOT|IN|BETWEEN|LIKE|EXISTS|ALL|ANY|SOME|[\+\-\*/%<>=~&\|\^])\s+)', flags=re.IGNORECASE | re.MULTILINE)
TSQL_JOIN_BASETABLE = re.compile(r'(?P<jointype>(FULL OUTER JOIN|LEFT OUTER JOIN|RIGHT OUTER JOIN|FULL JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|CROSS JOIN|SELF JOIN|JOIN|FROM))\s+(?P<basetable>[A-Za-z0-9_]+)(\s*|$)', flags=re.IGNORECASE | re.MULTILINE)
TSQL_RHSLHS_VARTABLE_NAMED = re.compile(r'[\"\[]?(?P<table>[<>@A-Za-z0-9_]+)[\"\]]?\.[\"\[]?(?P<varname>[<>@A-Za-z0-9_]+)[\"\]]?', flags=re.IGNORECASE | re.MULTILINE)
TSQL_RHSLHS_VARTABLE_UNNAMED = re.compile(r'[\"\[]?(?P<varname>[<>@A-Za-z0-9_]+)[\"\]]?', flags=re.IGNORECASE | re.MULTILINE)

# TSQL_ = re.compile(r'', flags=re.IGNORECASE | re.MULTILINE)

ODBC_KEYWORDS = {
	'ABSOLUTE',
	'ACTION',
	'ADA',
	'ADD',
	'ALL',
	'ALLOCATE',
	'ALTER',
	'AND',
	'ANY',
	'ARE',
	'AS',
	'ASC',
	'ASSERTION',
	'AT',
	'AUTHORIZATION',
	'AVG',
	'BEGIN',
	'BETWEEN',
	'BIT',
	'BIT_LENGTH',
	'BOTH',
	'BY',
	'CASCADE',
	'CASCADED',
	'CASE',
	'CAST',
	'CATALOG',
	'CHAR',
	'CHAR_LENGTH',
	'CHARACTER',
	'CHARACTER_LENGTH',
	'CHECK',
	'CLOSE',
	'COALESCE',
	'COLLATE',
	'COLLATION',
	'COLUMN',
	'COMMIT',
	'CONNECT',
	'CONNECTION',
	'CONSTRAINT',
	'CONSTRAINTS',
	'CONTINUE',
	'CONVERT',
	'CORRESPONDING',
	'COUNT',
	'CREATE',
	'CROSS',
	'CURRENT',
	'CURRENT_DATE',
	'CURRENT_TIME',
	'CURRENT_TIMESTAMP',
	'CURRENT_USER',
	'CURSOR',
	'DATE',
	'DAY',
	'DEALLOCATE',
	'DEC',
	'DECIMAL',
	'DECLARE',
	'DEFAULT',
	'DEFERRABLE',
	'DEFERRED',
	'DELETE',
	'DESC',
	'DESCRIBE',
	'DESCRIPTOR',
	'DIAGNOSTICS',
	'DISCONNECT',
	'DISTINCT',
	'DOMAIN',
	'DOUBLE',
	'DROP',
	'ELSE',
	'END',
	'END-EXEC',
	'ESCAPE',
	'EXCEPT',
	'EXCEPTION',
	'EXEC',
	'EXECUTE',
	'EXISTS',
	'EXTERNAL',
	'EXTRACT',
	'FALSE',
	'FETCH',
	'FIRST',
	'FLOAT',
	'FOR',
	'FOREIGN',
	'FORTRAN',
	'FOUND',
	'FROM',
	'FULL',
	'GET',
	'GLOBAL',
	'GO',
	'GOTO',
	'GRANT',
	'GROUP',
	'HAVING',
	'HOUR',
	'IDENTITY',
	'IMMEDIATE',
	'IN',
	'INCLUDE',
	'INDEX',
	'INDICATOR',
	'INITIALLY',
	'INNER',
	'INPUT',
	'INSENSITIVE',
	'INSERT',
	'INT',
	'INTEGER',
	'INTERSECT',
	'INTERVAL',
	'INTO',
	'IS',
	'ISOLATION',
	'JOIN',
	'KEY',
	'LANGUAGE',
	'LAST',
	'LEADING',
	'LEFT',
	'LEVEL',
	'LIKE',
	'LOCAL',
	'LOWER',
	'MATCH',
	'MAX',
	'MIN',
	'MINUTE',
	'MODULE',
	'MONTH',
	'NAMES',
	'NATIONAL',
	'NATURAL',
	'NCHAR',
	'NEXT',
	'NO',
	'NONE',
	'NOT',
	'NULL',
	'NULLIF',
	'NUMERIC',
	'OCTET_LENGTH',
	'OF',
	'ON',
	'ONLY',
	'OPEN',
	'OPTION',
	'OR',
	'ORDER',
	'OUTER',
	'OUTPUT',
	'OVERLAPS',
	'PAD',
	'PARTIAL',
	'PASCAL',
	'POSITION',
	'PRECISION',
	'PREPARE',
	'PRESERVE',
	'PRIMARY',
	'PRIOR',
	'PRIVILEGES',
	'PROCEDURE',
	'PUBLIC',
	'READ',
	'REAL',
	'REFERENCES',
	'RELATIVE',
	'RESTRICT',
	'REVOKE',
	'RIGHT',
	'ROLLBACK',
	'ROWS',
	'SCHEMA',
	'SCROLL',
	'SECOND',
	'SECTION',
	'SELECT',
	'SESSION',
	'SESSION_USER',
	'SET',
	'SIZE',
	'SMALLINT',
	'SOME',
	'SPACE',
	'SQL',
	'SQLCA',
	'SQLCODE',
	'SQLERROR',
	'SQLSTATE',
	'SQLWARNING',
	'SUBSTRING',
	'SUM',
	'SYSTEM_USER',
	'TABLE',
	'TEMPORARY',
	'THEN',
	'TIME',
	'TIMESTAMP',
	'TIMEZONE_HOUR',
	'TIMEZONE_MINUTE',
	'TO',
	'TRAILING',
	'TRANSACTION',
	'TRANSLATE',
	'TRANSLATION',
	'TRIM',
	'TRUE',
	'UNION',
	'UNIQUE',
	'UNKNOWN',
	'UPDATE',
	'UPPER',
	'USAGE',
	'USER',
	'USING',
	'VALUE',
	'VALUES',
	'VARCHAR',
	'VARYING',
	'VIEW',
	'WHEN',
	'WHENEVER',
	'WHERE',
	'WITH',
	'WORK',
	'WRITE',
	'YEAR',
	'ZONE',
    ')',
    '(',
    ';',
    ','
}

TYPEMAP = {
	'NVARCHAR': 'TEXT',
	'VARCHAR': 'TEXT',
	'NCHAR': 'TEXT',
	'CHAR': 'TEXT',
	'BINARY': 'TEXT',
	'VARBINARY': 'TEXT',
	'TEXT': 'TEXT',
	'TINYTEXT': 'TEXT',
	'MEDIUMTEXT': 'TEXT',
	'LONGTEXT': 'TEXT',
	'TINYBLOB': 'BLOB',
	'MEDIUMBLOB': 'BLOB',
	'LONGBLOB': 'BLOB',
	'BIT': 'INTEGER',
	'TINYINT': 'INTEGER',
	'BOOL': 'INTEGER',
	'SMALLINT': 'INTEGER',
	'MEDIUMINT': 'INTEGER',
	'INT': 'INTEGER',
	'INTEGER': 'INTEGER',
	'BIGINT': 'INTEGER',
	'SMALLMONEY': 'REAL',
	'MONEY': 'REAL',
	'FLOAT': 'REAL',
	'DOUBLE': 'REAL',
	'DECIMAL': 'REAL',
	'DEC': 'REAL',
	'REAL': 'REAL',
	'DATE': 'TEXT',
	'DATETIME': 'TEXT',
	'DATETIME2': 'TEXT',
	'SMALLDATETIME': 'TEXT',
	'DATETIMEOFFSET': 'TEXT',
	'TIMESTAMP': 'TEXT',
	'TIME': 'TEXT',
	'YEAR': 'TEXT'
}


